### ISSUE TITLE
Feature request - add page name to primary body class

### ISSUE THREAD

**Issue by mwilday** [moodle-an-hochschulen/moodle-local_staticpage#51]
We are wanting to use the static pages plugin to create landing pages for different bodies of users. My desire is to have a body class that is unique to the page that will allow me to brand that page differently than our others with CSS. If this isn't possible can you let me know? For now, I will use javascript to inject a body tag, but that is not a super sustainable solution. 
Thanks.

**Comment by Kordopatis** [comment]
Hi there!

Paste the below code before the closing tag.
works like a charm...

`<script>var body=document.body;body.classList.add("myclass");var body=document.body;body.classList.add("myclass");</script> `


Hope this help!

**Comment by abias** [comment]
Hi @mwilday , thank you for asking for this feature, and thank you @Kordopatis for proving an intermediate solution with JavaScript.

I have implemented this small feature now in https://github.com/moodleuulm/moodle-local_staticpage/commit/1f4c3953a2280544d9f8675b48f8a39fbac3d0e6 so that you can use it without any additional JavaScript.

Cheers,
Alex
